### ISSUE TITLE
Can't flash after serial monitor is used

### ISSUE THREAD

**Issue by microbit-carlos** [ARMmbed/dapjs#22]
I've been testing the latest DAPLink with WebUSB on the micro:bit and encountered the following issue: 

**Steps to reproduce**
* Flash micro:bit KL26 with WebUSB enabled DAPLink
* Go to https://armmbed.github.io/dapjs/examples/web.html (state on 31/05/2018)
* Choose: "DAPLink CMSIS-DAP" (micro:bit) 
* Connect: "BBC micro:bit"
* Flash binary: "Flash Green"
    * Flashing works as expected
* Serial monitor: "9600", "Start"
    * The KL26 status LED starts blinking
    * The expected text appears in the serial monitor box
* Serial monitor: "Stop"
    * KL26 status LED stops blinking
* Flash binary: "Frash Greeen"
    * The progress bar never starts and stays like this: 
     ![image](https://user-images.githubusercontent.com/29712657/40789464-6118fd22-64ea-11e8-9c31-8ef06e4b31b3.png)
    * The status LED for the KL26 keeps blinking at a "high speed" rate (same as a successful flash) indefinitely
* At this point I can only reset the current state by refreshing the page

**Comment by arekzaluski** [comment]
@microbit-carlos Thank you for reporting this issue. I can reproduce it on current master. I've fixed this issue in this PR: https://github.com/ARMmbed/dapjs/pull/21

**Comment by microbit-carlos** [comment]
Wow that was quick, thanks @arekzaluski!

**Comment by thegecko** [comment]
@microbit-carlos Can you confirm this is still an issue with the latest release?

**Comment by microbit-carlos** [comment]
Is there similar online example page I can use to test flashing and then serial?
The only a HTML file I can see in the examples projects is this one: https://armmbed.github.io/dapjs/examples/daplink-flash/web.html

**Comment by thegecko** [comment]
No, the serial example is now node-based

**Comment by microbit-carlos** [comment]
Right okay, maybe @microbit-sam can test in some of the work he's been doing with DAPJs?

**Comment by thegecko** [comment]
I have seen serial working for Sam, pleas reopen this issue if further issues are found.
